version: "3.8"
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./V1__init_product_data.sql:/docker-entrypoint-initdb.d/V1__init_product_data.sql
    ports:
      - "5432:5432"

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: warehouse
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command:
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    ports:
      - "8080:8080"

#  backend:
#    build: .
#    container_name: backend
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/warehouse
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
#      KEYCLOAK_REALM: hookah-cat
#      KEYCLOAK_RESOURCE: hookah-cat-core
#    depends_on:
#      - postgres
#      - keycloak
