server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /hookah-warehouse

#url properties
url:
  base: http://localhost:8081/

#postgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: hookah-cat-core
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/hookah-cat
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/hookah-cat

